function dc_code = get_dc_code(dct2C_tilde, DCTAB)
    dc = dct2C_tilde(1, :)';
    dc_diff = [dc(1);-diff(dc)];
    dc_diff_bin = arrayfun(@(i) my_d2b(dc_diff(i)), [1:length(dc_diff)], 'UniformOutput', false);
    dc_category = arrayfun(@(i) length(dc_diff_bin{i}), [1:length(dc_diff_bin)], 'UniformOutput',false);
    dc_category = cell2mat(dc_category) + 1;
    dc_code = ...
        arrayfun( ...
            @(i) [ ...
                DCTAB(dc_category(i), 2:(DCTAB(dc_category(i), 1) + 1)), ...
                dc_diff_bin{i}...
            ], ...
            [1:length(dc_diff)], ...
            'UniformOutput', ...
            false ...
        );
    dc_code = cell2mat(dc_code);
end
